defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: paymentscheduler
  host: localhost
  pool: 5
  password:

test:
  <<: *defaults

development:
  <<: *defaults

<% db = URI.parse(ENV['DATABASE_URL'] || 'postgres://localhost/calendar_development') %>

production:
  adapter: postgresql
  host: <%= db.host %>
  username: <%= db.user %>
  password: <%= db.password %>
  database: <%= db.path[1..-1] %>
  encoding: 'utf8'